import React, { useState } from 'react'
import { Button, Card, Col, Container, Row,  } from 'react-bootstrap'
import "../../Asserts/Style/AskQues.css";
import "../../Asserts/Style/Header.css";
import "../../Asserts/Style/Middle2.css";
import "../../Asserts/Style/About.css";
import "./que.css";
import IMAGES from '../../Asserts/Images';

function AskQues() {
 
    const cardDataa = [
        {
            question: 'How Does Aniquest work?',
            answer: 'Aniquest works by utilizing advanced natural language processing algorithms to generate human-like text based on the input it receives. Aniquest works by utilizing advanced natural language.',
          },
          {
            question: 'What texts can you generate with Aniquest?',
            answer: 'Aniquest can generate a wide range of texts, including articles, blog posts, creative writing, technical documentation, and more.',
          },
          {
            question: 'How does the Aniquest AI work?',
            answer: 'Aniquest AI analyzes input text, understands context and intent, and generates coherent and contextually relevant output text.',
          },
          {
            question: 'Can I try Aniquest for free?',
            answer: 'Yes, Aniquest offers a free trial for users to experience the capabilities of the AI before committing to a subscription.',
          },
          {
            question: 'Can the AI write stories or posts of +1000 words?',
            answer: 'Of course, our AI is trained to develop long texts, but we strongly recommend being as objective and specific with your definitions in order to get a perfect job.',
          },
          {
            question: 'Is the content generated by Aniquest AI original?',
            answer: 'Yes, the content generated by Aniquest AI is original and unique, tailored to the input and user requirements.',
          },
          {
            question: 'How can I make the AI check my texts?',
            answer: 'To have the AI check your texts, you can input your text into Aniquest, and it will provide suggestions, improvements, or generate content based on your input.',
          },
        ];

        const [expandedIndex, setExpandedIndex] = useState(4);

        const handleToggle = (index) => {
          setExpandedIndex(expandedIndex === index ? null : index);
      };
  return (
   <>
   <Container>

  <div>
   <h1 className=' FrequentlyAsked mb-5 '>
   Frequently Asked <br/> Questions
   </h1>
  </div>
  
  <div className="row Freq-shadow">
      {cardDataa.map((item, index) => (
        <Card key={index} className={`Frequently-Asked col-sm-12 ${index === expandedIndex ? 'expanded' : ''}`} onClick={() => handleToggle(index)}>
          <div className="form-check How-does d-flex  justify-content-between my-2">
            <label className="form-check-label " htmlFor={`flexRadioDefault${index + 1}`}>
              <h5 className="Text-Area">{item.question}</h5>
              {index === expandedIndex && item.answer && (
                <div>
                  <p className='perfectjob'>{item.answer}</p>
                </div>
              )}
            </label>
            <div className="Plus d-flex justify-content-center align-items-center">
              <img src={index === expandedIndex ? (IMAGES.MINUS) : IMAGES.PLUSS} className="d-flex justify-content-center align-items-center" alt="..." />
            </div>
          </div>
        </Card>
      ))}
    </div>

   </Container>
  
   <Container>
  <Row className="peoplefrsit border-0">
    <Col sm={12} md={6} lg={5}>
      <h2 className="my-5 d-flex justify-content-start mx-2 frsit-initiative">
        In the Service of our people frsit initiative
      </h2>
    </Col>
    <Col sm={12} md={6} lg={6} className="d-flex justify-content-start justify-content-md-end">
      <div className="Fan">
        <Button className='SignUpNow' variant="light">Sign Up Now</Button>{' '}
      </div>
    </Col>
  </Row>
</Container>

    
          <div className="MADDDD">
        <Container>
          <div>
            <Row className="my-0">
              <Col className="" sm={6} lg={3}>
                <h1 className="AII "> CLIENTS</h1>
                <span className="OL">Login </span>
                <Col className="my-2" sm={6} lg={3}>
                  <span className="OL">Sign Up </span>
                </Col>
              </Col>
              <Col className="" sm={6} lg={3}>
                <h1 className="AII"> SOCIAL MEDIA </h1>
                <span className="OL ">Twitter </span>
              </Col>

              <Col className="" sm={6} lg={3}>
                <h1 className="AII mt-2"> LEGAL INFO</h1>
                <span className="OL ">Legal information </span>
                <Col className="my-2" sm={6} lg={8}>
                  <span className="OL">Terms & Conditions </span>
                </Col>
                <Col className="my-2" sm={6} lg={8}>
                  <span className="OL">Privacy Policy </span>
                </Col>
              </Col>

              <Col className="" sm={6} lg={3}>
                <h1 className="AII"> SUPPORT</h1>
                <span className="OL">Helpdesk </span>
              </Col>
            </Row>
          </div>
        </Container>
      </div>
      <div className="mid4">
        <Container>
          <Col sm={6} lg={3}>
            <h1 className="OL my-3 "> T22 All right reserved</h1>
          </Col>
        </Container>
      </div>


   </>
  )
}

export default AskQues
